spring.application.name=pokemonTCGP
# PostgreSQL
# spring.datasource.url=jdbc:postgresql://db:5432/pokemondb
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemondb
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties
# API Configuration
pokemon.api.key=8e928576-d57e-4e52-a918-5c396c5978ca

produts.base-url=https://api.pokemontcg.io/v2

# Logging for WebClient (opcional)
# logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG